- Instead of having configure create scripts, use sed and give them execute permissions.

diff --git a/usb_ir/configure b/usb_ir/configure
--- a/usb_ir/configure
+++ b/usb_ir/configure
@@ -664,6 +664,7 @@ INSTALL_PROGRAM
 INSTALL_SCRIPT
 INSTALL_DATA
 SET_MAKE
+SED
 DYNLIB_EXT
 DYNMOD_EXT
 build
@@ -2792,6 +2793,90 @@ else
 echo "${ECHO_T}no" >&6; }
   SET_MAKE="MAKE=${MAKE-make}"
 fi
+
+{ echo "$as_me:$LINENO: checking for a sed that does not truncate output" >&5
+echo $ECHO_N "checking for a sed that does not truncate output... $ECHO_C" >&6; }
+if test "${ac_cv_path_SED+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+            ac_script=s/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb/
+     for ac_i in 1 2 3 4 5 6 7; do
+       ac_script="$ac_script$as_nl$ac_script"
+     done
+     echo "$ac_script" | sed 99q >conftest.sed
+     $as_unset ac_script || ac_script=
+     # Extract the first word of "sed gsed" to use in msg output
+if test -z "$SED"; then
+set dummy sed gsed; ac_prog_name=$2
+if test "${ac_cv_path_SED+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_path_SED_found=false
+# Loop through the user's path and test for each of PROGNAME-LIST
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_prog in sed gsed; do
+  for ac_exec_ext in '' $ac_executable_extensions; do
+    ac_path_SED="$as_dir/$ac_prog$ac_exec_ext"
+    { test -f "$ac_path_SED" && $as_test_x "$ac_path_SED"; } || continue
+    # Check for GNU ac_path_SED and select it if it is found.
+  # Check for GNU $ac_path_SED
+case `"$ac_path_SED" --version 2>&1` in
+*GNU*)
+  ac_cv_path_SED="$ac_path_SED" ac_path_SED_found=:;;
+*)
+  ac_count=0
+  echo $ECHO_N "0123456789$ECHO_C" >"conftest.in"
+  while :
+  do
+    cat "conftest.in" "conftest.in" >"conftest.tmp"
+    mv "conftest.tmp" "conftest.in"
+    cp "conftest.in" "conftest.nl"
+    echo '' >> "conftest.nl"
+    "$ac_path_SED" -f conftest.sed < "conftest.nl" >"conftest.out" 2>/dev/null || break
+    diff "conftest.out" "conftest.nl" >/dev/null 2>&1 || break
+    ac_count=`expr $ac_count + 1`
+    if test $ac_count -gt ${ac_path_SED_max-0}; then
+      # Best one so far, save it but keep looking for a better one
+      ac_cv_path_SED="$ac_path_SED"
+      ac_path_SED_max=$ac_count
+    fi
+    # 10*(2^10) chars as input seems more than enough
+    test $ac_count -gt 10 && break
+  done
+  rm -f conftest.in conftest.tmp conftest.nl conftest.out;;
+esac
+
+
+    $ac_path_SED_found && break 3
+  done
+done
+
+done
+IFS=$as_save_IFS
+
+
+fi
+
+SED="$ac_cv_path_SED"
+if test -z "$SED"; then
+  { { echo "$as_me:$LINENO: error: no acceptable $ac_prog_name could be found in \$PATH" >&5
+echo "$as_me: error: no acceptable $ac_prog_name could be found in \$PATH" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+else
+  ac_cv_path_SED=$SED
+fi
+
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_path_SED" >&5
+echo "${ECHO_T}$ac_cv_path_SED" >&6; }
+ SED="$ac_cv_path_SED"
+  rm -f conftest.sed
 
 
 DYNLIB_EXT=so
@@ -8006,7 +8091,7 @@ fi
 # Output some files
 ac_config_files="$ac_config_files Make.settings Makefile drivers/Makefile darwin/Makefile utils/Makefile scripts/Makefile reflasher/Makefile packaging/Makefile"
 
-ac_config_files="$ac_config_files autoconf/stamp-h setup.py iguanaIR.i utils/record-sends utils/clearID utils/writeLCD scripts/mode2-translator scripts/serial-test scripts/send-loop"
+ac_config_files="$ac_config_files autoconf/stamp-h iguanaIR.i setup.py"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -8571,14 +8656,8 @@ do
     "reflasher/Makefile") CONFIG_FILES="$CONFIG_FILES reflasher/Makefile" ;;
     "packaging/Makefile") CONFIG_FILES="$CONFIG_FILES packaging/Makefile" ;;
     "autoconf/stamp-h") CONFIG_FILES="$CONFIG_FILES autoconf/stamp-h" ;;
-    "setup.py") CONFIG_FILES="$CONFIG_FILES setup.py" ;;
     "iguanaIR.i") CONFIG_FILES="$CONFIG_FILES iguanaIR.i" ;;
-    "utils/record-sends") CONFIG_FILES="$CONFIG_FILES utils/record-sends" ;;
-    "utils/clearID") CONFIG_FILES="$CONFIG_FILES utils/clearID" ;;
-    "utils/writeLCD") CONFIG_FILES="$CONFIG_FILES utils/writeLCD" ;;
-    "scripts/mode2-translator") CONFIG_FILES="$CONFIG_FILES scripts/mode2-translator" ;;
-    "scripts/serial-test") CONFIG_FILES="$CONFIG_FILES scripts/serial-test" ;;
-    "scripts/send-loop") CONFIG_FILES="$CONFIG_FILES scripts/send-loop" ;;
+    "setup.py") CONFIG_FILES="$CONFIG_FILES setup.py" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -8688,6 +8767,7 @@ INSTALL_PROGRAM!$INSTALL_PROGRAM$ac_delim
 INSTALL_SCRIPT!$INSTALL_SCRIPT$ac_delim
 INSTALL_DATA!$INSTALL_DATA$ac_delim
 SET_MAKE!$SET_MAKE$ac_delim
+SED!$SED$ac_delim
 DYNLIB_EXT!$DYNLIB_EXT$ac_delim
 DYNMOD_EXT!$DYNMOD_EXT$ac_delim
 build!$build$ac_delim
@@ -8718,7 +8798,7 @@ SWIG_LIB!$SWIG_LIB$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 76; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 77; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
